repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-yaml
    - id: check-merge-conflict
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: detect-aws-credentials
      args:
        - '--allow-missing-credentials'
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
    - id: terraform_providers_lock
      exclude: >
          (?x)^(
              examples/.*$
          )$
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
      exclude: >
          (?x)^(
              examples/.*$
          )$
    - id: terraform_docs
      exclude: >
          (?x)^(
              examples/.*$
          )$
      args: [
        '--args=--sort-by required',
      ]
    - id: terraform_checkov
      args:
        - --args=--skip-check CKV_AWS_150
        - --args=--skip-check CKV_AWS_131
        - --args=--skip-check CKV_AWS_23
        - --args=--skip-check CKV_AWS_2
        - --args=--skip-check CKV_AWS_103
        - --args=--skip-check CKV2_AWS_20
        - --args=--skip-check CKV_AWS_66
        - --args=--skip-check CKV_AWS_158
